package housy.ledger;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;

public class MainFrame extends javax.swing.JFrame {

  private Ledger ledger;
  private File saveFile;
  private boolean edited;
  
  public MainFrame() {
    initComponents();
    ledger = new Ledger();
    setLedgerTableModel(ledger);
    reload();
    
    initIcon();
  }
  
  private void initIcon() {
    try {
      setIconImage(ImageIO.read(getClass().getResourceAsStream("/res/ledger.png")));
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(this, "Failed to load the programs icon!");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JPopupMenu.Separator();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenuItem4 = new javax.swing.JMenuItem();
    jSeparator2 = new javax.swing.JPopupMenu.Separator();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem6 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Transaction Ledger");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null},
        {null, null, null},
        {null, null, null},
        {null, null, null}
      },
      new String [] {
        "Date", "Value", "Message"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTable1);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jButton1.setText("Deposit");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);

    jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jButton3.setText("Withdraw");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton3);

    jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jButton4.setText("Remove");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton4);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setText("Total value: 0");
    jPanel1.add(jLabel1);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    jMenu1.setText("File");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem1.setText("New");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem1ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem2.setText("Load");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem2ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem2);
    jMenu1.add(jSeparator1);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem3.setText("Save");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem3);

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem4.setText("Save as");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem4ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem4);
    jMenu1.add(jSeparator2);

    jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    jMenuItem5.setText("Exit");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem5ActionPerformed(evt);
      }
    });
    jMenu1.add(jMenuItem5);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    jMenuItem6.setText("Change currency");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem6ActionPerformed(evt);
      }
    });
    jMenu2.add(jMenuItem6);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void showTransactionCreator(int mode) {
    TransactionCreator creator = new TransactionCreator(this, mode);
    creator.setVisible(true);
    int code = creator.getExitCode();
    
    if (code != TransactionCreator.SUCCESS) {
      return;
    }
    
    ledger.record(creator.getTransaction());
    reload();
    edited = true;
  }
  
  private void reload() {
    jTable1.revalidate();
    jTable1.repaint();
    DecimalFormat format = new DecimalFormat("#,##0.00");
    String total = format.format(ledger.getTotal().doubleValue());
    jLabel1.setText("Total:    " + total +  " " + ledger.getCurrencySymbol());
  }
  
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    showTransactionCreator(TransactionCreator.DEPOSIT);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    showTransactionCreator(TransactionCreator.WITHDRAW);
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int index = jTable1.getSelectedRow();
    if (index == -1) {
      return;
    }
    
    int ensurance = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this record?");
    if (ensurance != JOptionPane.YES_OPTION) {
      return;
    }
    
    ledger.remove(index);
    reload();
    edited = true;
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    exit();
  }//GEN-LAST:event_jMenuItem5ActionPerformed

  private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    CurrencySelector selector = new CurrencySelector(this);
    selector.setVisible(true);
    
    int exitCode = selector.getExitCode();
    if (exitCode != CurrencySelector.SUCCESS_CODE) {
      return;
    }
    
    ledger.setCurrencySymbol(selector.getSelectedSymbol());
    reload();
  }//GEN-LAST:event_jMenuItem6ActionPerformed

  private void save() {
    if (saveFile == null) {
      saveAs();
      return; //saveAs() calls save() and we don't want it to get recursive now do we?
    }
    
    try {
      Serializer.save(saveFile, ledger);
      edited = false;
    } catch (IOException e) {
      JOptionPane.showMessageDialog(this, "Failed to save the file!");
    }
  }
  
  private void exit() {
    if (edited) {
      int exitCode = JOptionPane.showConfirmDialog(this, "You have unsaved changes!\nWould you like to save them before exiting?");
      
      if (exitCode == JOptionPane.YES_OPTION) {
        save();
      }
    }
    
    System.exit(0);
  }
  
  private void newPage() {
    if (edited) {
      int exitCode = JOptionPane.showConfirmDialog(this, "You have unsaved changes!\nWould you like to save them before creating a new instance?");
      
      if (exitCode == JOptionPane.YES_OPTION) {
        save();
      }
    }
    
    ledger = new Ledger();
    saveFile = null;
    edited = false;
    setLedgerTableModel(ledger);
    reload();
  }
  
  private void load() {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new LedgerFileFilter());
    int exitCode = chooser.showOpenDialog(this);
    
    if (exitCode != JFileChooser.APPROVE_OPTION) {
      return;
    }
    
    File selectedFile = chooser.getSelectedFile();
    saveFile = selectedFile;
    ledger = Serializer.load(saveFile);
    setLedgerTableModel(ledger);
    reload();
  }
  
  private void saveAs() {
    JFileChooser chooser = new JFileChooser();
    chooser.setFileFilter(new LedgerFileFilter());
    int exitCode = chooser.showSaveDialog(this);
    
    if (exitCode != JFileChooser.APPROVE_OPTION) {
      return;
    }
    
    File selectedFile = chooser.getSelectedFile();
    
    if (!selectedFile.getName().endsWith(LedgerFileFilter.EXTENSION)) {
      selectedFile = new File(selectedFile.getAbsolutePath() + LedgerFileFilter.EXTENSION);
    }
    
    if (selectedFile.exists()) {
      int ensurance = JOptionPane.showConfirmDialog(this, "This file already exists!\nAre you sure you want to overwrite it?");
      
      if (ensurance != JOptionPane.YES_OPTION) {
        return;
      }
    }
    
    saveFile = selectedFile;
    save();
  }
  
  private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    saveAs();
  }//GEN-LAST:event_jMenuItem4ActionPerformed

  private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    load();
  }//GEN-LAST:event_jMenuItem2ActionPerformed

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    save();
  }//GEN-LAST:event_jMenuItem3ActionPerformed

  private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    newPage();
  }//GEN-LAST:event_jMenuItem1ActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    exit();
  }//GEN-LAST:event_formWindowClosing

  private void setLedgerTableModel(Ledger ledger) {
    jTable1.setModel(new LedgerTableModel(ledger));
    jTable1.getColumnModel().getColumn(LedgerTableModel.VALUE_INDEX).setCellRenderer(new DefaultTableCellRenderer() {
      @Override
      public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        ((JLabel) comp).setHorizontalAlignment(SwingUtilities.TRAILING);
        return comp;
      }
    });
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem4;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPopupMenu.Separator jSeparator1;
  private javax.swing.JPopupMenu.Separator jSeparator2;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
