package housy.ledger;

import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;

public class TransactionCreator extends javax.swing.JDialog {

  public static final int DEPOSIT = 1;
  public static final int WITHDRAW = 2;

  public static final int SUCCESS = 0;
  public static final int CANCELED = -1;

  private int currentMode;
  private Transaction value;
  private int exitCode = CANCELED;

  /**
   * Initializes the transaction creator according to the selected mode. parent
   * = the instance of the main frame. mode = one of the modes defined as static
   * integers.
   */
  public TransactionCreator(java.awt.Frame parent, int mode) {
    super(parent, true);
    initComponents();
    setLocationRelativeTo(parent);

    currentMode = mode;

    if (mode == DEPOSIT) {
      jButton1.setText("Deposit");
      setTitle("Deposit");
    }

    if (mode == WITHDRAW) {
      jButton1.setText("Withdraw");
      setTitle("Withdraw");
    }

    if (mode != DEPOSIT && mode != WITHDRAW) {
      throw new IllegalArgumentException("Invalid creator mode!");
    }

    PlainDocument document = (PlainDocument) jTextField1.getDocument();
    document.setDocumentFilter(new IntegerDocumentFilter());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setText("Amount");

    jLabel2.setText("Message");

    jButton1.setText("Record");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Cancel");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(jLabel1)
            .addComponent(jTextField1)
            .addComponent(jLabel2)
            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public Transaction getTransaction() {
    return value;
  }

  public int getExitCode() {
    return exitCode;
  }

  private boolean isNumeric(String str) {
    try {
      Double.parseDouble(str);
      return true;
    } catch (NumberFormatException e) {
      return false;
    }
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String msg = jTextField2.getText().trim();
    String value = jTextField1.getText().trim();

    if (value.isBlank()) {
      JOptionPane.showMessageDialog(this, "Please enter a value first!");
      return;
    }

    if (currentMode == WITHDRAW) {
      value = "-" + value;
    }

    if (!isNumeric(value)) {
      JOptionPane.showMessageDialog(this, "The specified value is not in a valid number format!\nMaybe you used to many dots?");
      return;
    }

    Transaction transaction = new Transaction(value, msg);
    this.value = transaction;
    exitCode = SUCCESS;
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
  }//GEN-LAST:event_jButton2ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  // End of variables declaration//GEN-END:variables
}
